timestep_respacing: 100
skip_timesteps: 25

lp_custom: 0
lp_custom_value: 0
lpips_sim_lambda: 1000
l2_sim_lambda: 10000
range_lambda: 50

deg_cone_projection: 0

clip_guidance_lambda: 0
classifier_lambda: 25

num_imgs: 6
batch_size: 6

gpu: 0

seed: 1

classifier_type: 3
second_classifier_type: -1
third_classifier_type: -1

use_blended: true


